version: 2.1
orbs:
  node: circleci/node@3.0.0

workflows:
  on-commit:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires:
            - install

  on-tag:
    jobs:
      - install:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build:
          requires:
            - install
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish:
          requires:
            - install
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

jobs:
  # Install all dependencies
  install:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Update npm
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

  # Run unit tests
  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12
    steps:
      - run:
          name: Run tests
          command: npm test

  # Build
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12
    steps:
      - run:
          name: Build Typescript
          command: npm run build

  publish:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12
    steps:
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish
